import type { Metadata } from "next";
import { inter as font } from "./fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased grid auto-rows-min justify-items-center mt-20 min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
