# Generated by Django 5.1.1 on 2024-09-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128, null=True)),
                ('price', models.IntegerField()),
                ('colour', models.CharField(max_length=128, null=True)),
                ('vendor', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
